travis:
  secure:
    BINSTAR_TOKEN: jWokKkoerkONNj8f53pGyj9jdkcReVlmX6td1vMSoNC8c+ukWWRgS8q4zdjoKbDuLEnDMlwKbm0EX1lGUoIHyJCdUcx+ryIOo2Jtk3+T9jDipzhB06bEEp0XP57dlxd4yM33xH6bPOvFr6zSLg69YxXfQ/Ty/PHS2PoofCpHtg1EKov1O5xjtrcqGJIlFJo8b6bTfRE9LY81WIuYOi+qjf5QJ32ym168VNRyri1SbtF7lMjZKdnHUQ7TxEfECcoYqnZ2dsRFLP4gJqmT1z9zMoRPgg1hVyjh/awSaCTJdyT5LC+GAApyCHMyv8kb80+bgHRzyIZIrKJyeRiAD/qvo3oKWEUp76Z0wW9aunkJQ8XOgR2OpGrTQ/7YDN2FApwmbRmorPSHvWLA2znwy62TPptCd8Df3V6oMa8LAQOF3460jgccqbrYExRK9ni9JUQaEaPr4oxrMGE7HMgyw+a7Lmt+KVKIQt2gevnr9OQCYUupSvW6adcRaduJnpT5/yLSJJ8V4hFDAIiSKjCqCkWpd4AanO6PIdYoFL8DeS7MQsv4a1pIgJkskU/GCAWX2Z4KFwmSnCN8W+XBLNxy+aO/z3MIzk2Anbt8yfEu4I9QLf/2ontLIfSXnXYOndwyAORFKLhwfjIU76V+E+te+ZQojrNkG3VdxccCBD8H49sgrYI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
